export const ROUTES = {
  MAIN: "/main",
  TARGETS: "/targets",
  COMUNITY: "/comunity",
  PRACTICE: "/practice",
  ERROR: "/error",
  LOGIN: "/login",
  PROFILE: "/profile",
  SUBSCRIPTION: "/profile/subscription",
  FAQ: "/profile/faq",
  TERMS: "/profile/terms",
  PRIVACY: "/profile/privacy",
  ARCHIVE: "/archive",
  BREATH: "/breath",
  META_CARD: "/meta-card",
  AUDIO_HELP: "/audio-help",
} as const;
