import plugin from 'tailwindcss/plugin';

export const semanticColorsPlugin = plugin(function ({ addUtilities }) {
  addUtilities({
    /* Backgrounds */
    '.bg-beige-primary': { backgroundColor: 'var(--background-beige-primary)' },
    '.bg-beige-secondary': { backgroundColor: 'var(--background-beige-secondary)' },
    '.bg-beige-tertiary': { backgroundColor: 'var(--background-beige-tertiary)' },
    '.bg-beige-quaternary': { backgroundColor: 'var(--background-beige-quaternary)' },
    '.bg-mustard-primary': { backgroundColor: 'var(--background-color-1-primary)' },
    '.bg-mustard-secondary': { backgroundColor: 'var(--background-color-1-secondary)' },
    '.bg-mustard-tertiary': { backgroundColor: 'var(--background-color-1-tertiary)' },
    '.bg-cold-green-primary': { backgroundColor: 'var(--background-color-2-primary)' },
    '.bg-cold-green-secondary': { backgroundColor: 'var(--background-color-2-secondary)' },
    '.bg-vinous-primary': { backgroundColor: 'var(--background-color-3-primary)' },
    '.bg-vinous-secondary': { backgroundColor: 'var(--background-color-3-secondary)' },
    '.bg-light-green-primary': { backgroundColor: 'var(--background-color-4-primary)' },
    '.bg-light-green-secondary': { backgroundColor: 'var(--background-color-4-secondary)' },
    '.bg-flesh-primary': { backgroundColor: 'var(--background-color-5-primary)' },
    '.bg-flesh-secondary': { backgroundColor: 'var(--background-color-5-secondary)' },
    '.bg-black-primary': { backgroundColor: 'var(--background-color-6-primary)' },
    '.bg-black-secondary': { backgroundColor: 'var(--background-color-6-secondary)' },
    '.bg-brown-primary': { backgroundColor: 'var(--background-color-7-default)' },
    '.bg-brown-secondary': { backgroundColor: 'var(--background-color-7-secondary)' },
    '.bg-red-primary': { backgroundColor: 'var(--background-danger-primary)' },
    '.bg-red-secondary': { backgroundColor: 'var(--background-danger-secondary)' },
    '.bg-green-primary': { backgroundColor: 'var(--background-success-primary)' },
    '.bg-green-secondary': { backgroundColor: 'var(--background-success-secondary)' },
    '.bg-yellow-primary': { backgroundColor: 'var(--background-warning-primary)' },
    '.bg-yellow-secondary': { backgroundColor: 'var(--background-warning-secondary)' },
    '.bg-white-primary': { backgroundColor: 'var(--background-white-primary)' },
    '.bg-white-secondary': { backgroundColor: 'var(--background-white-secondary)' },
    '.bg-white-tertiary': { backgroundColor: 'var(--background-white-tertiary)' },
    /* Texts */
    '.text-beige-primary': { color: 'var(--text-beige-primary)' },
    '.text-beige-secondary': { color: 'var(--text-beige-secondary)' },
    '.text-black-primary': { color: 'var(--text-black-primary)' },
    '.text-black-secondary': { color: 'var(--text-black-secondary)' },
    '.text-brown-primary': { color: 'var(--text-brown-primary)' },
    '.text-brown-secondary': { color: 'var(--text-brown-secondary)' },
    '.text-cold-green-primary': { color: 'var(--text-cold-green-primary)' },
    '.text-cold-green-secondary': { color: 'var(--text-cold-green-secondary)' },
    '.text-flesh-primary': { color: 'var(--text-flesh-primary)' },
    '.text-flesh-secondary': { color: 'var(--text-flesh-secondary)' },
    '.text-green-primary': { color: 'var(--text-green-primary)' },
    '.text-green-secondary': { color: 'var(--text-green-secondary)' },
    '.text-light-green-primary': { color: 'var(--text-light-green-primary)' },
    '.text-light-green-secondary': { color: 'var(--text-light-green-secondary)' },
    '.text-mustard-primary': { color: 'var(--text-mustard-primary)' },
    '.text-mustard-secondary': { color: 'var(--text-mustard-secondary)' },
    '.text-red-primary': { color: 'var(--text-red-primary)' },
    '.text-red-secondary': { color: 'var(--text-red-secondary)' },
    '.text-vinos-primary': { color: 'var(--text-vinos-primary)' },
    '.text-vinos-secondary': { color: 'var(--text-vinos-secondary)' },
    '.text-white-primary': { color: 'var(--text-white-primary)' },
    '.text-white-secondary': { color: 'var(--text-white-secondary)' },
    '.text-yellow-primary': { color: 'var(--text-yellow-primary)' },
    '.text-yellow-secondary': { color: 'var(--text-yellow-secondary)' },
  });
});
